### ISSUE TITLE
flakyness

### ISSUE THREAD

**Issue by ekiwi** [YosysHQ/setup-oss-cad-suite#5]
I really love your OSS CAD tool builds and the Chisel community has come to rely on them. Unfortunately the github action to set them up has been very flaky, especially on MacOS, but also on Linux lately. We ended up replacing it with our own action: https://github.com/chipsalliance/chisel3/pull/2901

Just wanted to let you know in case this is useful for improving your Github action. Thank you so much for providing the binaries!

**Comment by mmicko** [comment]
Thanks you for feedback, and sorry to hear about issues. If you could provide more info about failure you got it would be great, so I could work on improving this.

**Comment by ekiwi** [comment]
This is the text log:

```
2023-01-09T16:20:41.5831835Z ##[group]Run YosysHQ/setup-oss-cad-suite@v1
2023-01-09T16:20:41.5832062Z with:
2023-01-09T16:20:41.5832253Z   osscadsuite-version: 2022-08-18
2023-01-09T16:20:41.5832482Z   python-override: false
2023-01-09T16:20:41.5832679Z ##[endgroup]
2023-01-09T16:20:41.6364730Z ##[group]Installing OSS CAD Suite
2023-01-09T16:20:41.6383960Z [command]/home/runner/work/_actions/YosysHQ/setup-oss-cad-suite/v1/dist/install-oss-cad-suite linux-x64 2022-08-18
2023-01-09T16:20:41.6445937Z ~/work/_temp/.setup-oss-cad-suite ~/work/_temp
2023-01-09T16:20:41.6911942Z ##[error]The process '/home/runner/work/_actions/YosysHQ/setup-oss-cad-suite/v1/dist/install-oss-cad-suite' failed with exit code 1
2023-01-09T16:20:41.6969989Z Post job cleanup.
```

**Comment by lethalbit** [comment]
From what I can gather this seems to be that the github API returns something other than the expected result causing the `build` variable to be unset, or set to an invalid result causing the `wget` to fail.

A potential fix would be to check if `build` is valid and if not, wait a while and try again. Maybe using something like `curl -Is $build | head -1 | cut -c 8-` then to check if the HTTP response code is good or not and if it's not delay abit then try again.

Another fix would be to do-away with the shell component of the action all together and to the API request and download in JavaScript, then to do something like ensuring the request succeeded or not.


Yet another, but less ideal option, would be to have a fixed known "good" URL to grab from in case the build fails, seeing as the release names and targets are well known, it might be possible to compute the URL for the release and just stagger it by a day in case the latest fails.


In either case this wouldn't solve the problem is the API request is fine but the actual download of the rease is causing problems. It's hard to say without any debug introspection into the action as it runs fine 100% of the time locally for me, so I suspect it's a GitHub CI issue itself with rate limiting

**Comment by lethalbit** [comment]
@ekiwi sorry for the direct ping, but the updated version of the action should now be much more stable, especially as you can now use the `${{ secrets.GITHUB_TOKEN }}` to allow the action to use the authenticated API, which should prevent the random failures due to it hitting the public API rate limit on the CI worker, which turned out to be the main cause.

**Comment by lethalbit** [comment]
@mmicko this Issue should likely be closed at this point.

**Comment by mmicko** [comment]
Agree, done and thanks for your work @lethalbit
